[theme]
base="light"
primaryColor="#18453B"         # MSU green
backgroundColor="#FFFFFF"      # White
secondaryBackgroundColor="#E6ECE9"  # Light gray-green for contrast
textColor="#1A2521"           # Dark gray for readability
font="sans serif"